version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=dbusername
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=simpleBank

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DBSOURCE=postgresql://dbusername:dbpassword@postgres:5432/simpleBank?sslmode=disable
    depends_on:
      - postgres
    # entrypoint in compose will override the entrypoint in dockerfile, it will
    # also clear out any default command on the image, such as the CMD on dockerfile 
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]

    # hence we specify the command
    command: ["/app/main"]

